stone:
  roles:
      - name: 'Role-Stone-Brick'
        display_name: 'Stone Brick'
        description: 'Builder front website with zero code'
        type: 'main'
        permissions:

          - name: 'Permission-stone-brick'
            display_name: 'Access Stone Brick'
            description: 'Permission Builder Stone Brick'
